/*JSON object with content for different cities*/
let point_json = 
{
    "new_york": {
        "name": "New York",
        "section1": "<a href = \"https://www.elevenmadisonpark.com/\"><img src = \"images/ny2.jpg\" alt = \"image of eleven madison park\"><\/a><p><span><a href = \"https://www.elevenmadisonpark.com/\">Eleven Madison Park<\/a><\/span> is a fine dining restaurant located in the heart of New York City. It ranked third among The World's 50 Best Restaurants in 2016 and topped the list in 2017. The restaurant has been owned by Chef Daniel Humm since 2011 and during that time it has evolved considerably, both in food and in experience. Today, the restaurant offers an eight to ten course menu in the main dining room, but guests can also visit the bar for a more abbreviated tasting menu, some light snacks, or simply for a cocktail or glass of wine.<\/p>",
        "section2": "<a href = \"https://www.starbucksreserve.com/en-us/menus\"><img src = \"images/NewYork/starbucks_nyc.jpeg\" alt = \"image of starbucks reserve\"> </a> <p><span><a href = \"https://www.starbucksreserve.com/en-us/menus\">Starbucks Reserve Roastery<\/a><\/span> is a place for coffee lovers, where starbucks roast their own coffee beans. They also have experimental drinks, which cannot be found anywhere else. Some Starbucks Reserve coffee is sold in about 1,500 of the chain's traditional outlets. This is one of the handful Starbucks Reserve Roasteries in the entire world.<\/p>",
        "section3": "<a href = \"https://thehalalguys.com/\"><img src = \"images/ny1.webp\" alt = \"image of the halal guys\"><\/a> <p><span><a href = \"https://thehalalguys.com/\">The Halal Guys<\/a><\/span> is one of the oldest and the most recognized places of New York's street food. The Halal Guys is mostly recognized by its primary dish which is a platter of chicken or gyro meat with rice, though it also serves a chicken or gyro wrap sandwich. Both locals and tourists love this spot on the streets of New York.<\/p>",
        "section4": "<a href = \"https://www.230-fifth.com/?gclid=CjwKCAiAnvj9BRA4EiwAuUMDf5tekW2lGhV7YZqvNodAmwn-DJBy4qgLqjMheQdFZmgrMXKS2hYuFRoC80AQAvD_BwE\"><img src = \"images/230_fifth.jpg\" alt = \"images of 230 fifth rooftop bar\"><\/a><p><span><a href = \"https://www.230-fifth.com/?gclid=CjwKCAiAnvj9BRA4EiwAuUMDf5tekW2lGhV7YZqvNodAmwn-DJBy4qgLqjMheQdFZmgrMXKS2hYuFRoC80AQAvD_BwE\">230 Fifth<\/a><\/span> is New York's largest outdoor Rooftop Garden and Fully enclosed Penthouse Lounge. This is a great place to enjoy the night with both friends and family. 230 Fifth puts as much emphasis on their nightlife attractions as they do their delicious recipes. They serve dishes such as sea bass, vegetarian chow fun noodles, cuban sandwiches, fried calamari, spring rolls, slow cooked beef. They also have drinks like peach bellini, mango jalapeno margherita, pineapple moscow mule and many more. They offer several fully loaded bars with loud music coming from New York’s best DJ’s.<\/p>"
    },

    "tokyo" : {
        "name": "Tokyo",
        "section1": "<a href = \"https://whereintokyo.com/venues/25239.html\"><img src = \"images/Tokyo/800-shibu-foodshow5.jpg\" alt = \"image of Tokyu FoodShow\"><\/a><p>Located in the basement of the Tokyu Department Store next to the east exit of Shibuya Station, this sprawling food hall, <span><a href = \"https://whereintokyo.com/venues/25239.html\">Tokyu Foodshow<\/a><\/span> is one of the biggest and most varied in town. They prepare foods of all kinds - tonkatsu, sushi, grilled chicken, tofu products, pickles, deli salads, and all kinds of bento boxes. This basement food court is one of the hidden gems in the food scene.<\/p>",
        "section2": "<a href = \"https://www.ramenguidejapan.com/reviews/2018/11/5/ramenya-toybox-best-shoyu-ramen-minowa\"><img src = \"images/Tokyo/tk1.jpg\" alt = \"image of Ramenya Toybox\"><\/a><p>One cannot end a trip to Japan without experiencing Ramen. <span><a href = \"https://www.ramenguidejapan.com/reviews/2018/11/5/ramenya-toybox-best-shoyu-ramen-minowa\">Ramenya Toybox<\/a><\/span> is one of the most highly rated ramen shops in the city. Toybox uses a handpicked selection of the best Nagoya Cochin chicken. The most popular bowl here is the pictured Shoyu Ramen. In addition to using handpicked, high quality chicken, the chef here also uses a variety of 5-7 of the best shoyu soy sauces in Japan which best pair with his chicken broth. This is a great place for dinner after a busy day exploring the city.<\/p>",
        "section3": "<a href = \"https://www.timeout.com/tokyo/restaurants/tempura-motoyoshi-imo#:~:text=As%20its%20name%20suggests%2C%20Tempura,imo%20means%20potato%20in%20Japanese).\"><img src = \"images/Tokyo/tk4.jpg\" alt = \"image of Tempura Motoyoshi Imo\"><\/a><p><span><a href = \"https://www.timeout.com/tokyo/restaurants/tempura-motoyoshi-imo#:~:text=As%20its%20name%20suggests%2C%20Tempura,imo%20means%20potato%20in%20Japanese).\">Tempura Motoyoshi Imo</a><\/span> is one of Tokyo’s most celebrated tempura specialists. Located in the Shibuya region of Tokyo, this is a new but popular Tempura place. This place has great icecreams which can be paired with a modern take on tempura, the traditional Japanese deep fried fish. As its name suggests, Tempura Motoyoshi Imo is a takeaway store offering one of its sister restaurant’s signature items – the deep-fried sweet potato tempura (imo means potato in Japanese).<\/p>",
        "section4": " <a href = \"https://www.residentadvisor.net/club.aspx?id=16967\"><img src = \"images/Tokyo/tk3.jpg\" alt = \"image of Oath, nightclub\"><\/a><p>Originally located along a hidden pathway, <span><a href = \"https://www.residentadvisor.net/club.aspx?id=16967\">Oath<\/a><\/span> moved its location to Shibuya’s Trump Room in 2018, an underground club that has long been popular among trendy young Tokyo fashionistas. A tiny black door leads you into a room decked with chandeliers, lamps, mirrors and even a stuffed deer, creating an elegant and opulent interior. Oath hosts some of the world’s best underground DJs and serves high-quality drinks; the doors stay open until 8am on Saturdays and Sundays, meaning it’s the ideal place to go for a nijikai (after-party).<\/p>"
    },

    "london" : {
        "name": "London ",
        "section1": "<a href = \"https://dinnerbyheston.co.uk/\"><img src = \"images/London/dinner_by_heston_blumingthal(1).jpg\" alt = \"image of dinner by heston\"><\/a><p><span><a href = \"https://dinnerbyheston.co.uk/\">Dinner by Heston<\/a><\/span> is a 3 Michelin starred restaurant located in Knightsbridge. Tourists visit London to eat at this establishment. A reservation is must, and are hard to come by, so plan a trip after snagging a reservation. Some of the dishes here are unique and will not be found anywhere else in the world. The restaurant is headed by former Fat Duck head chef Ashley Palmer-Watts. Menu items are based on historical British dishes, which were researched by food historians and through the British Library. The restaurant intends to change the menu every three months, each menu containing historical dishes ranging from the 14th to 19th centuries.<\/p>",
        "section2": "<a href = \"https://www.teabythetaw.co.uk/\"><img src = \"images/London/tea_by_the_taw_(1).jpg\" alt = \"image of tea by the taw\"></a><p><span><a href = \"https://www.teabythetaw.co.uk/\">Tea by Taw<\/a></span> is located in Barnstaple North Devon sitting alongside the beautiful view of the river Taw. This tea stall is a comfy tea cafe and it won the best cafe award in the food, drink and tourism awards in 2016.  If one wants to experience the full tea culture of UK, this is a good place to try it out. Taste some awesome tea, with a meal that goes perfectly with the cup of tea. They also serve cream teas, traditional Vintage High teas, lunches and a selection of homemade cakes.<\/p>",
        "section3": "<a href = \"https://boroughmarket.org.uk/\"><img src = \"images/London/borough-market(1).jpg\" alt = \"image of borough market\"><\/a><p><span><a href = \"https://boroughmarket.org.uk/\">Burough market<\/a></span> is a wholesale and retail market hall in Southwark, London. It is considered to be London's street food heaven with roots from the 12th century. There are many highly rated food stalls in this market to satisfy any craving a hungry tourist might have. From British fruits and vegetables to international delicacies, handmade chocolate truffles, Indian street food and raclette, there’s plenty to peruse and tuck into from the many traders and restaurants at one of London’s oldest food markets.<\/p>",
        "section4": "<a href = \"https://www.fabriclondon.com/\"><img src = \"images/London/Fabric.jpg\" alt = \"image of fabric, nightclub\"></a><p><span><a href = \"https://www.fabriclondon.com/\">Fabric<\/a></span> is one of the capital's most famous clubbing spots located in Farringdon. Founded in 1999 on Charterhouse Street opposite Smithfield Market, the club was voted World Number 1 Club in DJ Magazine's \"Top 100 Clubs Poll\" in 2007 and 2008 and ranked World Number 2 in 2009, 2010 and 2017. The legendary London club features three rooms, including one with a “bodysonic” dancefloor, and has hosted some of the world's biggest DJs. One will find electro, techno and disco music, as well as drum’n’bass and grime, pumping from the speakers.<\/p>"
    }
}

/*display the content of the respective city selected*/
function fill_content() {
    let url_string = window.location.href;
    let url = new URL(url_string);
    let city = url.searchParams.get("city"); //finding the selected city based on the URL parameter
    let content;
    if(city == "new_york") {
        content = point_json.new_york;
    } else if (city == "tokyo") {
        content = point_json.tokyo;
    } else {
        content = point_json.london;
    }
    document.title = content.name;
    document.getElementById("header").innerHTML = content.name;
    document.getElementById("section1").innerHTML = content.section1;
    document.getElementById("section2").innerHTML = content.section2;
    document.getElementById("section3").innerHTML = content.section3;
    document.getElementById("section4").innerHTML = content.section4;
}

fill_content();
